### ISSUE TITLE
Does cross_validate not support multiclassification?

### ISSUE THREAD

**Issue by wakamezake** [nyanp/nyaggle#36]
https://gist.github.com/wakamezake/5864abcebb3a5a2951af29de81a7ec97

**Comment by wakamezake** [comment]
sorry, I forgot to make "predict_proba is True".
https://nyaggle.readthedocs.io/en/latest/source/reference/validation.html#nyaggle.validation.cross_validate

**Comment by nyanp** [comment]
@wakamezake 
Thanks for your comment!
I think nyaggle should automatically choose the right method instead of exposing `predict_proba` parameter. I’ll try to implement it.
