### ISSUE TITLE
pytest tmpdir fixture

### ISSUE THREAD

**Issue by harupy** [nyanp/nyaggle#48]
This is not an issue. I found you use `get_temp_directory` in the tests to create a temporary directory. Is there any reason that you don't use the `tmpdir` fixture in pytest?

https://docs.pytest.org/en/latest/tmpdir.html#the-tmpdir-fixture

**Comment by nyanp** [comment]
Thank you for your comment!
I didn’t know the `tmpdir` fixture. It seems better to replace `get_temp_directory` with it.
If you can make a PR for this issue, contributions are welcome :)

**Comment by harupy** [comment]
I'll open a PR!
