### ISSUE TITLE
Flatten logging parameters to improve readability

### ISSUE THREAD

**Issue by nyanp** [nyanp/nyaggle#63]
In `run_experiment`, model_params and fit_params are stored as string to distinguish them from other parameters and it makes difficult to compare params across experiments.

It seems better to flatten the dictionary as in the PR below.
https://github.com/mlflow/mlflow/pull/1863

#### Before
```json
{
    "fit_params": "{ early_stopping_rounds: 100 }",
    "model_params": "{ max_depth: 3, objective: \"binary\" }",
    "algorithm_type": "lgbm"
}
```

#### After
```json
{
    "fit_params.early_stopping_rounds": 100,
    "model_params.max_depth": 3,
    "model_params.objective": "binary",
    "algorithm_type": "lgbm"
}
```

**Comment by harupy** [comment]
Can I work on this?
