### ISSUE TITLE
Question about docstring

### ISSUE THREAD

**Issue by tenajima** [nyanp/nyaggle#69]
https://github.com/nyanp/nyaggle/blob/d5dd9cf387def52a41bfb4d15fc07195fb9392c7/nyaggle/validation/split.py#L69

This `split`  should be `folds` ?

**Comment by tenajima** [comment]
https://github.com/nyanp/nyaggle/blob/d5dd9cf387def52a41bfb4d15fc07195fb9392c7/nyaggle/validation/split.py#L52

https://github.com/nyanp/nyaggle/blob/d5dd9cf387def52a41bfb4d15fc07195fb9392c7/nyaggle/validation/split.py#L117

These are also.

**Comment by nyanp** [comment]
You’re correct, folds is much better.

**Comment by tenajima** [comment]
I made simple PR !
