### ISSUE TITLE
Drop Python v3.5 support

### ISSUE THREAD

**Issue by wakamezake** [nyanp/nyaggle#86]
Wouldn't it be better to match the Python version supported by the library(XGBoost/LightGBM)?

- XGBoost
  - > Breaking: XGBoost Python package now requires Python 3.6 and later ([#5715](https://github.com/dmlc/xgboost/pull/5715)) - 
  - Python v3.6^ support
- LightGBM
  -  https://pypi.org/project/lightgbm/
  - Python v3.5^ support

**Comment by nyanp** [comment]
@wakamezake 
Sorry for late reply, I think now it is reasonable to drop Python 3.5 support.
