### ISSUE TITLE
remove experiment-tracking topic label from the project

### ISSUE THREAD

**Issue by zhimin-z** [nyanp/nyaggle#94]
This project aims for examples of code competition rather that an experiment-tracking tool, I wonder if the repo holder minds tweaking the topic labels a bit. @nyanp

**Comment by nyanp** [comment]
@zhimin-z 
Thanks for the suggestion, [nyaggle actually has a small code for experiment tracking](https://github.com/nyanp/nyaggle/blob/master/nyaggle/experiment/experiment.py), but the main use of nyaggle is to provide a simple implementation for data science competitions.
I have removed experiment-tracking label from topics :)
